version: "3.7"
services:
  rabbit:
    image: rabbitmq:latest

  fastapi:
    image: jeremyleo/fastapi-celery-mq-example:latest
    ports:
      - 8080:8080
    entrypoint: uvicorn app:app --host 0.0.0.0 --port 8080

  worker:
    image: jeremyleo/fastapi-celery-mq-example:latest
    entrypoint: celery --app worker.celery_app worker -c 2 --loglevel=info